#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_erlang="$(erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:format(erlang:binary_to_list(Version)), halt().' -noshell 2>/dev/null || true)"
  jq -n --arg erlang "$ver_erlang" '{erlang: $erlang}'
}

version "$@"
